export const cities: string[] = [
    "Jerusalem",
    "Tel Aviv",
    "Haifa",
    "Ashdod",
    "Rishon Leziyyon",
    "Petah Tikva",
    "Beersheba",
    "Netanya",
    "Holon",
    "Bnei Brak",
    "Rehovot",
    "Bat Yam",
    "Ramat Gan",
    "Ashkelon",
    "Modiin",
    "Herzliya",
    "Kfar Saba",
    "Raanana",
    "Hadera",
    "Bet Shemesh",
    "Lod",
    "Modiin Ilit",
    "Ramla",
    "Nahariyya",
    "Qiryat Ata",
    "Givatayim",
    "Qiryat Gat",
    "Acre",
    "Eilat",
    "Afula",
    "Karmiel",
    "Hod HaSharon",
    "Tiberias",
    "Qiryat Motzkin",
    "Qiryat Yam",
    "Rosh HaAyin",
    "Ness Ziona",
    "Qiryat Bialik",
    "Ramat Hasharon",
    "Dimona",
    "Yavne",
    "Or Yehuda",
    "Yehud",
    "Safed",
    "Gedera",
    "Netivot",
    "Mevasseret",
    "Ofakim",
    "Arad",
    "Gan Yavne",
    "Qiryat Shemona",
    "Kfar Yona",
    "Maalot",
    "Nesher",
    "Sderot",
    "Elad",
    "Givat Shmuel",
    "Kiryat Ono",
    "Tirat Carmel",
    "Yokneam Illit"
]
