export const cities: string[] = [
    "Jerusalem",
    "Tel Aviv",
    "Haifa",
    "Ashdod",
    "Rishon Leziyyon",
    "Petah Tikva",
    "Beersheba",
    "Netanya",
    "Holon",
    "Bnei Brak",
    "Rehovot",
    "Bat Yam",
    "Ramat Gan",
    "Ashkelon",
    "Modiin",
    "Herzliya",
    "Kfar Saba",
    "Raanana",
    "Hadera",
    "Bet Shemesh",
    "Lod",
    "Ramla",
    "Nahariyya",
    "Givatayim",
    "Qiryat Gat",
    "Acre",
    "Eilat",
    "Afula",
    "Karmiel",
    "Hod HaSharon",
    "Tiberias",
    "Rosh HaAyin",
    "Ness Ziona",
    "Ramat Hasharon",
    "Dimona",
    "Yavne",
    "Or Yehuda",
    "Yehud",
    "Safed",
    "Netivot",
    "Ofakim",
    "Arad",
    "Ariel",
    "Maale Adumim",
    "Qiryat Shemona",
    "Nesher",
    "Sderot",
    "Elad",
    "Givat Shmuel",
    "Kiryat Ono",
]
