export const cities: string[] = [
    "Jerusalem",
    "Tel Aviv",
    "Haifa",
    "Ashdod",
    "Rishon Leziyyon",
    "Beersheba",
    "Netanya",
    "Rehovot",
    "Bat Yam",
    "Ramat Gan",
    "Herzliya",
    "Kfar Saba",
    "Hadera",
    "Bet Shemesh",
    "Ramla",
    "Nahariyya",
    "Qiryat Gat",
    "Eilat",
    "Afula",
    "Hod HaSharon",
    "Tiberias",
    "Ness Ziona",
    "Ramat Hasharon",
    "Dimona",
    "Yavne",
    "Or Yehuda",
    "Yehud",
    "Netivot",
    "Ofakim",
    "Qiryat Shemona",
    "Nesher",
    "Sderot",
]
